import styles from './page.module.css';
import { Metadata } from 'next';
import MainScreen from '@/components/MainScreen/MainScreen';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

export default function Home() {
  return <MainScreen />;
}
